PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/wiko/s4750/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/wiko/s4750/etc,system/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/wiko/s4750/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/wiko/s4750/vendor,system/vendor)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/wiko/s4750/xbin,system/xbin)
